-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 18:43:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema learn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema learn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learn` DEFAULT CHARACTER SET utf8 ;
USE `learn` ;

-- -----------------------------------------------------
-- Table `learn`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`institucion` (
  `id` INT NOT NULL,
  `provincia` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(16) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `institucion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `institucion_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_institucion`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `learn`.`institucion` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`curso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `esPublico` TINYINT NOT NULL,
  `institucion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `institucion_id`),
  CONSTRAINT `fk_curso_institucion`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `learn`.`institucion` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `learn`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`modulo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `curso_id`),
  CONSTRAINT `curso_id`
    FOREIGN KEY (`curso_id`)
    REFERENCES `learn`.`curso` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`ejercicio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `modulo_id` INT NOT NULL,
  `tipo_de_ejercicio` VARCHAR(45) NOT NULL,
  `dificultad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `modulo_id`),
  CONSTRAINT `modulo_id`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `learn`.`modulo` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`respuesta` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `es_correcta` TINYINT NOT NULL,
  `ejercicio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ejercicio_id`),
  INDEX `ejercicio_id_idx` (`ejercicio_id` ASC) VISIBLE,
  CONSTRAINT `ejercicio_id`
    FOREIGN KEY (`ejercicio_id`)
    REFERENCES `learn`.`ejercicio` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`respuesta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`respuesta_usuario` (
  `id` INT NOT NULL,
  `respuesta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `respuesta_id`),
  CONSTRAINT `respuesta_id`
    FOREIGN KEY (`respuesta_id`)
    REFERENCES `learn`.`respuesta` (`id`),
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `learn`.`usuario` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`curso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`curso_usuario` (
  `id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `curso_id`),
  CONSTRAINT `fk_curso_usuario_curso`
    FOREIGN KEY (`curso_id`)
    REFERENCES `learn`.`curso` (`id`),
  CONSTRAINT `fk_curso_usuario_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `learn`.`usuario` (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
